clc;
clear all;
close all;
%%
addpath('..');
addpath('../CHINESE(MANDARIN)');
load('Speech4.mat');
s1=Speech4(1,:);
s2=Speech4(4,:);
s3=Speech4(2,:);
s1=s1/max(abs(s1));
s2=s2/max(abs(s2));
s3=s3/max(abs(s3));
%%
%Training,Phase
Tw=30;
Ts=10;
alpha=0.97;
M=20;
C=12;
K=128;
L=22;
Fs=8000;
LF=300;
HF=3700;
%%
%[MFCCs,FBEs,frames]=mfcc(speech,Fs,Tw,Ts,alpha,@hamming,[LF,HF],M,C+1,L);
fid=fopen('mfccs1','rb');
vectors=fread(fid,'double');
fclose(fid);
MFCCs=reshape(vectors,13,2048);
MFCCs=MFCCs-repmat(mean(MFCCs,2),1,size(MFCCs,2));
[fbes,W]=ica_signal(MFCCs(2:end,:),C,1);
[Priors,Mu,Sigma]=EM_init_kmeans(fbes,K);
[Priors,Mu,Sigma]=EM(fbes,Priors,Mu,Sigma);
%%
fid=fopen('mfccs2','rb');
speech1=fread(fid,'short');
speech1=speech1/32768;
fclose(fid);
[MFCCs1,FBEs1,frames1]=mfcc(speech1,Fs,Tw,Ts,alpha,@hamming,[LF,HF],M,C+1,L);
[fbes1,W1]=ica_signal(MFCCs1(2:end,:),C,1);
[Priors1,Mu1,Sigma1]=EM_init_kmeans(fbes1,K);
[Priors1,Mu1,Sigma1]=EM(fbes1,Priors1,Mu1,Sigma1);
%%
fid=fopen('mfccs3','rb');
speech2=fread(fid,'short');
speech2=speech2/32768;
fclose(fid);
[MFCCs2,FBEs2,frames2]=mfcc(speech2,Fs,Tw,Ts,alpha,@hamming,[LF,HF],M,C+1,L);
[fbes2,W2]=ica_signal(MFCCs2(2:end,:),C,1);
[Priors2,Mu2,Sigma2]=EM_init_kmeans(fbes2,K);
[Priors2,Mu2,Sigma2]=EM(fbes2,Priors2,Mu2,Sigma2);
%%
%Test,Phase
p=[];
p1=[];
p2=[];
fid=fopen('mfccs','rb');
speech3=fread(fid,'short');
speech3=speech3/32768;
fclose(fid);
[MFCCs3,FBEs3,frames3]=mfcc(speech3,Fs,Tw,Ts,alpha,@hamming,[LF,HF],M,C+1,L);
u=mean(MFCCs3,2);
MFCCs3=MFCCs3-repmat(u,1,size(MFCCs3,2));
fbes3=W*MFCCs3(2:end,:);
fbes4=W1*MFCCs3(2:end,:);
fbes5=W2*MFCCs3(2:end,:);%exp[-(x1-u1)'*inv(cov)*(x1-u1)/2]
for m=1:1:K,
    p(:,m)=Priors(m)*gaussPDF(fbes3,Mu(:,m),Sigma(:,:,m));%exp(-(x-u)*inv(cov)*(x-u)'/2)
end
p=log(sum(p,2));
for m=1:1:K,
    p1(:,m)=Priors1(m)*gaussPDF(fbes4,Mu1(:,m),Sigma1(:,:,m));
end
p1=log(sum(p1,2));
for m=1:1:K,
    p2(:,m)=Priors2(m)*gaussPDF(fbes5,Mu2(:,m),Sigma2(:,:,m));
end
p2=log(sum(p2,2));
a1=[];
a2=[];
a3=[];
for k=1:1:length(p),
    a1(k,1)=sum(p(1:k));
    a2(k,1)=sum(p1(1:k));
    a3(k,1)=sum(p2(1:k));
end
